swagger: '2.0'

host: localhost:8085
basePath: /animals-api/v1

info:
  version: 1.0.0
  title: Animals API
  description: Administra o cadastro de animais do sistema.
  termsOfService: http://localhost:8085/animals-api/v1/termos-de-uso
  contact:
    name: Contato
    url: http://localhost:8085/animals-api/v1/contato
    email: contato@animalsapi.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT



paths:
  '/animal/cadastrar':
    post:
      summary: Cadastra animal
      description: Cadastra um novo animal
      consumes:
        - application/json
      produces:
        - application/json
      operationId: cadastraAnimal
      parameters:
        - in: body
          name: animal_
          schema:
            $ref: '#/definitions/Animal'
      responses:
        201:
          description: Cadastro efetuado com sucesso!
          schema:
            $ref: '#/definitions/Animal'
        400:
          description: Requisição inválida
        500:
          description: Erro interno no servidor. Tente novamente mais tarde.
      
        
definitions:

  Animal:
    type: object
    properties:
      id: 
        type: integer
        format: int64
        example: 1
      nome:
        type: string
        example: Billy
      tipo:
        type: string
        example: Cachorro
      dataNascimento:
        type: string
        format: date
      sexo:
        type: string
        enum: [M, F]
      dataRegistro:
        type: string
        format: date
      